### ISSUE TITLE
Inconsistent docker-compose file 

### ISSUE THREAD

**Issue by zargha** [Informatievlaanderen/VSDS-LDES-E2E-testing#73]
### The Problem
While running e2e-test/use-cases/gipod/4.time-fragment-ldes, docker compose fails to run because `ldes-server-simulator` doesnt start up.

### Error logs
```
Error response from daemon: invalid mount config for type "bind": bind source path does not exist: /home/tests/Tests/informatievlaanderen/VSDS-LDES-E2E-testing/e2e-test/support/data/empty
```

In env.time-fragment: [LDES_SERVER_SIMULATOR_SEED_FOLDER=../../../../ldes-server-simulator/data/empty](https://github.com/Informatievlaanderen/VSDS-LDES-E2E-testing/blob/main/e2e-test/use-cases/gipod/4.time-fragment-ldes/env.time-fragment#L4)

docker-compose.yaml:
```
  ldes-server-simulator:
    container_name: ${USECASE_NAME:-simulator-workflow-server-mongo}_ldes-server-simulator
    image: ghcr.io/informatievlaanderen/ldes-server-simulator:${LDES_SERVER_SIMULATOR_TAG}
    env_file:
      - env.simulator
    environment:
      - BASEURL=http://ldes-server-simulator
      - SEED=/tmp/data
    ports:
      - ${LDES_SERVER_SIMULATOR_PORT}:80
    volumes:
      - type: bind
        source: ${LDES_SERVER_SIMULATOR_SEED_FOLDER}
        target: /tmp/data
```
